name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:

    runs-on: ubuntu-latest

    
        
 
    steps:
    - uses: actions/checkout@v2
    
      with:
        
    - run: npm ci

   
